name: Build and Push

on:
  push:
    branches:
      - main

env:
  IMAGE: registry.digitalocean.com/jan-systems-registry/somebook:latest
  DO_DOCKER_LOGIN: ${{ secrets.DO_DOCKER_LOGIN }}

jobs:
  website:
    name: Build and Push
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://book.jan.systems

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Login to Digitalocean registry
      - name: Log in to Digitalocean registry
        run: docker login -u ${DO_DOCKER_LOGIN} -p ${DO_DOCKER_LOGIN} registry.digitalocean.com

      # Build the Docker image
      - name: Build image
        run: docker build -t ${IMAGE} .

      # Push the Docker image to Google Container Registry
      - name: Push image to registry
        run: docker push ${IMAGE}
